### ISSUE TITLE
Using admin's auth for public users

### ISSUE THREAD

**Issue by devth** [caribou/caribou-admin#3]
1. Caribou is really great, thanks for making it!
2. Not sure where the best place is to get help—didn't see a google group or anything. Are github issues ok or is there a better place?
3. I'm using caribou to build a json API. I saw that caribou-admin has all the stuff for login, password reset, etc, and thought it would be nice if I could reuse all that instead of baking my own. Since it has roles too, I figured I could make a "consumer" role for public users of the API and reserve the "admin" role for myself. Does this make sense or would it be a mess? I wouldn't want consumers to ever be able to login into _admin, or even know it existed.

**Comment by noisesmith** [comment]
1) glad you like it so far

2) here works, we also hang out on #caribou on IRC for more informal / realtime back and forth

3) You could create a user with a default-mask of 0 (meaning no access to any models in the admin), but this seems a bit silly, given you aren't even planning on letting them use the admin. The user model is currently tied in to admin access. Instead, you should create a new model with a similar structure to user (ie. having a password field and a collection of permissions tied to some models representing the data / functionality they access etc). The work needed to build your own user model is quite a bit less than the work you would need to do to make users that can't access the admin.

**Comment by devth** [comment]
Got it, thanks!
